name: CICD

on:
  push:
    branches:
      - main

env:
  PROJECT_JAR_NAME: cicd-test-0.0.1-SNAPSHOT.jar

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create application.yaml
        run: |
          echo "${{ secrets.APPLICATION_YAML }}" > src/main/resources/application.yaml

      - name: Java Setup
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'eclipse-temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew clean build -x test

      - name: Upload build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: cicd-test-0.0.1-SNAPSHOT.jar
          path: build/libs/${{ env.PROJECT_JAR_NAME }}

      - name: Upload Dockerfile
        uses: actions/upload-artifact@v4
        with:
          name: my-dockerfile
          path: Dockerfile
