name: CICD

on:
  push:
    branches:
      - main

env:
  PROJECT_JAR_NAME: cicd-test-0.0.1-SNAPSHOT.jar

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create application.yaml
        run: |
          echo "${{ secrets.APPLICATION_YAML }}" > src/main/resources/application.yaml

      - name: Java Setup
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew clean build -x test

      - name: Upload build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: my-jar
          path: build/libs/${{ env.PROJECT_JAR_NAME }}

      - name: Upload Dockerfile
        uses: actions/upload-artifact@v4
        with:
          name: my-dockerfile
          path: Dockerfile

  integration:
    needs: build
    runs-on: ubuntu-latest
    env:
      DOCKER_IMAGE_NAME: my-image

    steps:
      - name: Download JAR Artifact
        uses: actions/download-artifact@v4
        with:
          name: my-jar
          path: build/libs

      - name: Download Dockerfile Artifact
        uses: actions/download-artifact@v4
        with:
          name: my-dockerfile
          path: .

      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and Push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.DOCKER_IMAGE_NAME }}:latest .
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.DOCKER_IMAGE_NAME}}:latest